on:
  push:
    branches:
    - main

name: Deploy to S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Build the new ui
      id: build-static-assets
      env:
        BUCKET_NAME: marketsseer.com-root
      run: |
        npm ci
        npm run build
        aws s3 sync build s3://marketsseer.com-root
